In [1]:
import os
import pandas as pd

C:\Users\Justin-Laptop\AppData\Local\Temp\ipykernel_18728\3571106454.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# Define the folder path containing the CSV files
#folder_path = f'D:/!!Research/rgee_test/GEE_LPC/point_data/mesq_location_predictions/poly{poly_num}/env_batch_csv'
folder_path = f'C:/Users/Justin-Laptop/Documents/Research/GEE_LPC/point_data/inat_mesq_obsv/inat_points_env_data/env_batch_csv'

# Initialize an empty list to store DataFrames
dfs = []

# Iterate through each file in the folder
for file in os.listdir(folder_path):
    if file.endswith('.csv'):
        # Read the CSV file into a DataFrame
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)
        
        # Append the DataFrame to the list
        dfs.append(df)

# Concatenate all DataFrames in the list into a single DataFrame
merged_df = pd.concat(dfs, ignore_index=True)

# Display or do further processing with the merged DataFrame
merged_df.head()

,bd_0_5,bd_5_15,bd_15_30,bd_30_60,bd_60_100,bd_100_200,clay_0_5,clay_5_15,clay_15_30,clay_30_60,...,rf_025,water_storage,bio12,bio07,dist_drain,dist_road,GrndTruth,system:index,latitude,longitude
0,1.122422,1.169453,1.229453,1.181328,1.35,1.419531,8.851562,13.878906,24.906250,32.066406,...,0.165881,5.351870,342.137604,366.356262,55.044297,927.217160,1.0,00000000000000004efd,-800311.9975,-1.068035e+06
1,1.134434,1.176660,1.236660,1.207754,1.35,1.419531,8.611328,13.278320,23.945312,33.387695,...,0.210816,8.412261,331.502960,370.506927,73.649055,186.350529,1.0,00000000000000005132,-765893.6725,-1.028052e+06
2,1.139316,1.179590,1.239590,1.218496,1.35,1.419531,8.513672,13.034180,23.554688,33.924805,...,0.155755,5.216179,304.248871,371.458649,42.312752,805.548683,1.0,000000000000000050cf,-753913.1971,-1.023450e+06
3,1.140000,1.180000,1.240000,1.220000,1.35,1.419531,8.500000,13.000000,23.500000,34.000000,...,0.208645,9.009182,312.130066,371.018097,111.333754,994.238778,1.0,0000000000000000136e,-819255.0055,-9.966541e+05
4,1.140000,1.180000,1.240000,1.220000,1.35,1.419531,8.500000,13.000000,23.500000,34.000000,...,0.152246,18.310341,317.207519,374.482300,247.937284,5.192538,1.0,00000000000000003be0,-802377.0038,-1.065106e+06

In [4]:
# Export the merged DataFrame to a CSV file
#output_csv_path = f'D:/!!Research/rgee_test/GEE_LPC/point_data/mesq_location_predictions/poly{poly_num}/poly{poly_num}_env_data.csv'
output_csv_path = f'C:/Users/Justin-Laptop/Documents/Research/GEE_LPC/point_data/inat_mesq_obsv/inat_points_env_data/inat_points_env_data.csv'
merged_df.to_csv(output_csv_path, index=False)

print("Merged DataFrame has been exported to:", output_csv_path)

Merged DataFrame has been exported to: C:/Users/Justin-Laptop/Documents/Research/GEE_LPC/point_data/inat_mesq_obsv/inat_points_env_data/inat_points_env_data.csv